config/routes.rb
Rails.application.routes.draw do
  get 'visitors/index'

  get '/sitemap' => 'visitors#sitemap',
      defaults: { :format => 'xml' }

  get '/food' => 'articles#food',
      defaults: { :format => 'xml' }
  get '/live-events' => 'articles#live_events',
      defaults: { :format => 'xml' }
  get '/adventure' => 'articles#adventure',
      defaults: { :format => 'xml' }
  get '/shopping' => 'articles#shopping',
      defaults: { :format => 'xml' }

  resources :share_emails

  get '/santa-cruz-restaurant-week', to: 'articles#scrw', as: :santa_cruz_restaurant_week
  get '/lineup/food', to: 'articles#index', as: :food_lineup, :defaults => { :tag => 'food' }
  get '/lineup/live-events', to: 'articles#index', as: :live_events_lineup, :defaults => { :tag => 'live events' }
  get '/lineup/adventure', to: 'articles#index', as: :adventure_lineup, :defaults => { :tag => 'adventure' }
  get '/lineup/shopping', to: 'articles#index', as: :shopping_lineup, :defaults => { :tag => 'shopping' }

  resources :articles, :path => "/lineup" , :except => [:new, :create, :edit, :update, :destroy] do
    resources :events
    resources :locations
    get 'add/:article_id', to: 'articles#add', as: :add_to
    get 'remove/:article_id', to: 'articles#remove', as: :remove_from
    put :recommend, on: :member
    put :unrecommend, on: :member
    get 'change_status/:status', to: 'articles#change_status', as: :change_status, on: :member
  end

  get 'send_mail', to: 'articles#send_mail', as: :send_mail

  get 'tagged' => 'articles#tagged', :as => 'tagged'

  mount StripeEvent::Engine => '/stripe'


  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: 'omniauth_callbacks'}, skip: [:sessions, :registrations]

  #->Prelang (user_login:devise/stylized_paths)
  devise_scope :user do
    root to: 'users/registrations#new'
    get 'admin/users/:id', to: 'admin/users#edit', as: :edit_admin_user
    put 'admin/users/:id', to: 'admin/users#update'
    get 'admin/users', to: 'admin/users#new', as: :new_admin_user
    put 'add_tag/:tag', to: 'users/registrations#add_tag', as: :add_tag
    put 'remove_tag/:tag', to: 'users/registrations#remove_tag', as: :remove_tag
    delete "admin/users/:id" => "admin/users#destroy", as: :delete_user_admin
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    match '/users/:id/finish_signup' => 'users/registrations#finish_signup', via: [:get, :patch], :as => :finish_signup


    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
    post 'admin/add_role/:id/:role', to: 'admin/users#add_role', as: :add_role


  end

  authenticated :user do
    devise_scope :user do
      root to: 'articles#index', as: :authenticated
    end
  end

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    get 'article/:id', to: 'articles#edit', as: :edit_article
    get 'articles', to: 'articles#new', as: :new_article
    delete 'articles/:id', to: 'articles#destroy', as: :destroy_article
    put 'articles', to: 'articles#create'
    patch 'article/:id', to: 'articles#update'
    put 'article/:id', to: 'articles#update'
    delete 'articles/:id', to: 'articles#delete', as: :delete_article
  end


  # mount using default path: /email_processor
  mount_griddler


end

app/models/article.rb
class Article < ActiveRecord::Base
  validates_presence_of :title, :body
  validates_numericality_of :user_id

  belongs_to :user
  has_many :events, -> { order(start_date: :desc) }, dependent: :destroy
  has_many :locations, dependent: :destroy
  has_many :statuses, dependent: :destroy
  has_many :recommendations, dependent: :destroy
  has_many :recommended_users, :through => :recommendations, :source => :user


  acts_as_taggable
  acts_as_taggable_on

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  default_scope {order("publish_date DESC") }

  after_create :status_default

  accepts_nested_attributes_for  :events
  accepts_nested_attributes_for :locations

  scope :active, -> { where('publish_date <= ?', Time.current).order('publish_date DESC') }
  scope :next, lambda { |id| where("id > ?", id).order("id ASC")}


  scope :popular, -> {
    joins('LEFT OUTER JOIN recommendations ON articles.id = recommendations.article_id')
    .select('articles.*, count(recommendations.id) as "user_count"')
    .group('articles.id')
    .order('user_count desc')
  }


  mount_uploader :image, ImageUploader


  def next
    Article.active.where("articles.id > ?", self.id).order("id ASC").first
  end

  def previous
    Article.active.tagged_with(["tags", "food", "adventure", "liveevent", "shopping", "tinyvacation", "location"], :on => :tags, :any => true).where("articles.id < ?", self.id).order("id ASC").last
  end

  def find_status(status)
   return !!self.statuses.find_by_status(status)
  end

  def self.status(status)
    where(:statuses => {:status => status}).joins(:statuses)
  end


  def status_default
    self.statuses.build
    self.save
  end

  def current_week?
    date = Date.today.beginning_of_week
    return (date..date + 6.days).to_a
  end

  def word_count
    body.split.size
  end

  def reading_time
    (word_count / 200.0).ceil
  end

  def normalize_friendly_id(string)
    string.to_s.gsub("\'", "").parameterize
  end

  scope :popular, -> {
    joins('LEFT OUTER JOIN recommendations ON articles.id = recommendations.article_id')
    .select('articles.*, count(recommendations.id) as "user_count"')
    .group('articles.id')
    .order('user_count desc')
  }


end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_article, only: [:edit, :update, :destroy]

  # GET /articles/new
  def new
    @article = Article.new
    @article.locations.build
    @article.events.build
  end

  # GET /articles/1/edit
  def edit
  end

  # article /articles
  # article /articles.json
  def create
    @article = current_user.articles.build(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to admin_path, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to admin_path, notice: 'Article was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    render nothing: true
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :subhead, :body, :slug, :origin, :image, :publish_date, :user_id, :why, :tips, :tag_list, :tags, statuses_attributes: [:status, :article_id], locations_attributes: [], events_attributes: [] )
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :recommend, :unrecommend, :change_status]

  # GET /articles
  # GET /articles.json
  def index
    if params[:tag].present?
      @tag = ActsAsTaggableOn::Tag.find_by_name(params[:tag])
      @articles = Article.status(1).active.tagged_with(@tag).popular
      if current_user.present?
        @user = current_user
        @user_tags = @user.tag_list
      end
    elsif current_user.present?
       @user = current_user
       @user_tags = @user.tag_counts_on(:tags).limit(10)
       @articles = Article.tagged_with(@tags, :any => :true).status(1).active.popular
    else
      @articles = Article.status(1).active
    end
    @upcoming = Article.status(1).active.joins(:events).where("events.start_date >= ? and events.start_date <= ?", Date.today.beginning_of_week, Date.today.beginning_of_week + 6 ).popular.limit(5)

    respond_to do |format|
      format.html
      format.atom
    end
  end

   def scrw
    @tag = ActsAsTaggableOn::Tag.find_by_name('santa cruz restaurant week')
    @articles = Article.status(1).active.tagged_with(@tag)
    cart_ids = REDIS.sort(current_user_cart, :by => 'NOSORT', :get => ['Id:*->article_id','Id:*->price','Id:*->title', '#' ])
    @cart_line_items = cart_ids
    respond_to do |format|
      format.html
      format.atom
    end
  end

  def live_events
    @tag = ActsAsTaggableOn::Tag.find_by_name('live events')
    @articles = Article.status(1).active.tagged_with(@tag)
    respond_to do |format|
      format.atom
    end
  end

  def adventure
    @tag = ActsAsTaggableOn::Tag.find_by_name('adventure')
    @articles = Article.status(1).active.tagged_with(@tag)
    respond_to do |format|
      format.atom
    end
  end

  def food
    @tag = ActsAsTaggableOn::Tag.find_by_name('food')
    @articles = Article.status(1).active.tagged_with(@tag)
    respond_to do |format|
      format.atom
    end
  end

  def shopping
    @tag = ActsAsTaggableOn::Tag.find_by_name('shopping')
    @articles = Article.status(1).active.tagged_with(@tag)
    respond_to do |format|
      format.atom
    end
  end

  def send_mail
    send_mail = params[:send_mail]
    email = send_mail[:email]
    user = User.find_or_create_by(email: email)
    cart_ids = REDIS.sort(current_user_cart, :by => 'NOSORT', :get => ['Id:*->article_id','Id:*->title', '#' ])
    cart_line_items = cart_ids
    LineupMailer.send_email(email, cart_line_items).deliver
    REDIS.flushall
    render :nothing => :true
  end

  def add
    incr_id = REDIS.incrby(:id,  1)
    @id = "Id:#{incr_id}"
    line_item = REDIS.hmset(@id,  :article_id, params[:article_id], :title, params[:title])
    REDIS.sadd current_user_cart, incr_id
    REDIS.expire(@id, 30.minutes)
    if request.xhr?
      render json: { id: params[:id] }
    else
    end
  end

  def remove
    id = REDIS.hmget(current_user_cart,  params[:article_id])
    REDIS.srem current_user_cart, id.id
    render :js => "window.location = window.location"

  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    cart_ids = REDIS.sort(current_user_cart, :by => 'NOSORT', :get => ['Id:*->article_id','Id:*->price','Id:*->title', '#' ])
    @cart_line_items = cart_ids
    @related_articles = @article.find_related_tags.active.limit(5)
    @share = ShareEmail.new({ title: @article.title, file: @article.image.medium, url: url_for(@article) })
  end

  def tagged
    if params[:tag].present?
      @articles = Article.tagged_with(params[:tag])
    else
      @articles = Article.all
    end
  end

  def recommend
    @user = current_user
    @user.recommend(@article)
    if request.xhr?
      render json: { count: @article.recommended_users.count, id: params[:id] }
    else
      redirect_to @article
    end
  end

  def unrecommend
    @user = current_user
    @user.unrecommend(@article)
    if request.xhr?
      render json: { count: @article.recommended_users.count, id: params[:id] }
    else
      redirect_to @article
    end
  end

  def change_status
    @articles = Article.all
    @article.statuses.build(status: params[:status])
    if params[:status] = "published"
      @article.publish_date = Time.current
    end
    @article.save
    respond_to do |format|
      format.js
    end
  end

  private

    def current_user_cart
      "cart#{session[:session_id]}"
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :subhead, :body, :slug, :origin, :image, :publish_date, :user_id, :tag_list, statuses_attributes: [:status, :article_id], locations_attributes: [:line_1, :line_2, :city, :state_or_province, :postal_code] )
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.haml
%article
  - if defined?(index) && index
    - unless params[:tag].present?
      - for tag in article.tags
        - if current_user.present?
          - if @user_tags.include?(tag)
            .tag.center
              = tag
        -elsif article.tags.present?
          .tag
            = link_to tag, articles_path(:tag => tag)
    .title= link_to article.title, article
    .subtitle= article.subhead
    %small.info
      - if article.events.present?
        = article.events.first.start_date.strftime("%A, %b %d")
        @
        = article.events.first.start_date.strftime("%l:%M%P")
      - if article.locations.present?
        at
        = article.locations.first.line_1 + ","
        = article.locations.first.city
        = link_to "map", "http://maps.apple.com/maps?q=#{article.locations.first.latitude},#{article.locations.first.longitude}", :class => "tag-button"
    .hero= image_tag article.image.hero unless article.image.blank?
    %small.info
      - if article.publish_date.present?
        published
        = time_ago_in_words(article.publish_date)
        ago
      - if article.recommended_users.present?
        • recommended by
        = article.recommended_users.count
        - if article.recommended_users.count > 1
          people
        - else
          person
    .body
      %p= Nokogiri::HTML.parse(markdown(article.body)).css('p').first.text
  - else
    %h1= article.title
    %h2.subtitle= article.subhead
    %small.info
      - if article.publish_date.present?
        = time_ago_in_words(article.publish_date)
        ago • found in:
      - for tag in article.tags
        = link_to tag, articles_path(:tag => tag.name), :class => "tag-button"
    .hero= image_tag article.image.hero
    - if article.events.present? or article.why.present? or article.tips.present?
      %label.margin-toggle{:for => "mn-dates"}
        ⊕ Info
      %input#mn-dates.margin-toggle{:type => "checkbox"}/
      %span.marginnote
        - for event in article.events
          - if event.start_date > Time.current
            %h3.first= custom_time_distance(event.start_date)
          - else
            %h3.first
              = time_ago_in_words(event.start_date)
              ago
          %p.fa.fa-calendar
            = event.start_date.strftime("%A, %b %d")
          %p
            @
            = event.start_date.strftime("%l:%M%P")
            - if event.end_date.present?
              to
              - if event.start_date.day == event.end_date.day
                - if event.start_date.time != event.end_date.time
                  = event.start_date.strftime("%l:%M%P")
              - else
                = event.end_date.strftime("%A, %b %d")
                @
                = event.end_date.strftime("%l:%M%P")
        - if article.why.present?
          %h3 Why?
          %p= article.why
        - if article.tips.present?
          %h3 Tips
          - for tip in article.tips.split(',')
            %p.tip.fa.fa-check= tip
    - if article.locations.present?
      %label.margin-toggle{:for => "mn-location"}
        ⊕ Location
      %input#mn-location.margin-toggle{:type => "checkbox"}/
      %span.marginnote
        = render partial: 'location', locals: { article: article }
    .body= markdown(article.body)

  .readnext
    - if defined?(index) && index
      %small.readmore
        = link_to article do
          Read more
      %span.pull-right
        %i.fa.fa-bullhorn
        %span.recommend-count{'data-id' => '#{@article.id}'}
          = article.recommended_users.count
        %i.star.fa.fa-star-o
    - else
      - if current_user.present?
        -if current_user.recommended?(article)
          = link_to unrecommend_article_path(article), class: 'vote recommended', method: :put, remote: true, data: { toggle_href: recommend_article_path(article), id: article.id, toggle_class: 'recommend' } do
            %i.fa.fa-bullhorn
        - else
          = link_to recommend_article_path(article), class: 'vote recommend', method: :put, remote: true, data: { toggle_href: unrecommend_article_path(article), id: article.id, toggle_class: 'recommended'  } do
            %i.fa.fa-bullhorn
      - else
        %i.fa.fa-bullhorn
      %span.recommend-count
        = article.recommended_users.count
      - unless article.recommended_users.blank?
        .recommend-users
          - for user in article.recommended_users[0,10]
            = image_tag user.identities.first.avatar.thumb, :class => "circle" unless user.identities.first.blank?
      - if current_user.present?
        - if @cart_line_items.to_s.include? article.id.to_s
          %i.star.fa.fa-star.orange
        - else
          =link_to "", article_add_to_path(article_id: article.id, title: article.title), remote: true, class: "star fa fa-star-o", role: 'button', data: {toggle_href: "", toggle_class: 'fa-star'}
      %span.share
        %a.btn-2
          %i.fa.fa-share
        .share-popover
          = link_to "", onclick: "window.open('http://www.facebook.com/sharer/sharer.php?href=#{article_url(@article)}', 'newwindow', 'width=600, height=300'); return false;" do
            %i.fa.fa-3x.fa-facebook-official
          = link_to "", onclick: "window.open('http://twitter.com/share?text=#{@article.title} via @santacruzdaily&url=#{article_url(@article)}', 'newwindow', 'width=600, height=300'); return false;" do
            %i.fa.fa-3x.fa-twitter-square
          %a.btn
            %i.fa.fa-3x.fa-envelope
        .email-popover
          = render 'share_form'

:javascript
  $('.btn-2').click(function (e) {
    $('.share-popover').toggle();
    return false;
  });

  $('document').ready(function() {
    var regexp = /\b((?:[a-z][\w-]+:(?:\/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}\/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?«»“”‘’]))/i;

    $('article').innerHTML = aHref.match(/([\w\d\-_]*\.)+(\w*$|\w*\/[\w\d]*)/)[0];
  });

app/views/articles/_lineup_email.html.haml
.popover-title
  You are almost ready for Restaurant Week!
.popover-body
  = simple_form_for :send_mail, url: send_mail_path(:email), remote: true, format: :json, method: :get do |f|
    = f.input :email, placeholder: 'Your email address',label: false

    .hidden
      = f.input :nickname, :hint => 'Leave this field blank!'

    %div
      %a.coa{ onclick: "$('.send_mail').submit()"} Send my restaurant list
      %br
      .small By receiving this personalized email, you will be the first to know about our launch. We will never share or sell your information.
      %br
      %a.simplemodal-close.text Nevermind, I don't like food.


:javascript

  $('i').click(function (e) {
    $('.lineup-popover').modal();
    return false;
  });

  $(document).on('ajax:success', '.send_mail', function(e, data, status, xhr) {
    if (data.success) {
      $('.lineup-popover').hide();
      return $('.btn').hide();
    } else {
      $('.lineup-popover').hide();
      $('#simplemodal-container').hide();
      $('#simplemodal-overlay').hide();
      $('.btn').hide();
      return $('h1').text("Sent!");
    }
  });

app/views/articles/_location.html.haml
%h3.first
  %span.fa.fa-map-pin
  The Spot
- for location in article.locations do
  %p
    = location.line_1
    = location.line_2 unless location.line_2.blank?
    %br
    = "#{location.city}, #{location.state_or_province} #{location.postal_code}"
  = link_to image_tag( "https://maps.googleapis.com/maps/api/staticmap?size=315x315&zoom=15&amp;center=37.787,-122.413&markers=color:orange%7Clabel:A%7C#{location.latitude},#{location.longitude}"), "http://maps.apple.com/maps?q=#{location.latitude},#{location.longitude}", :target => "_blank"

app/views/articles/index.html.haml
- content_for :head do
  %meta{property: "og:title", content: "Santa Cruz Daily"}
  %meta{property: "og:site_name", content: "Santa Cruz Daily"}
  %meta{property: "og:description", content: "Welcome to Santa Cruz Daily, a place to discover and make plans for living, visiting and adventuring in Santa Cruz."}
  %meta{property: "og:type", content: "website"}
  %meta{property: "og:url", content: request.url}
  %meta{property: "fb:admins", content: "750702877"}
  %meta{name: "twitter:title", content: "Santa Cruz Daily"}
  %meta{name: "twitter:description", content: "Welcome to Santa Cruz Daily, a place to discover and make plans for living, visiting and adventuring in Santa Cruz."}
  %meta{name: "twitter:card", content: "summary"}
  %meta{name: "twitter:domain", content: "santacruzdaily.com"}
  %meta{name: "twitter:creator", content: "@santacruzdaily"}
  %meta{itemprop: "headline", content: "Santa Cruz Daily"}
  %meta{itemprop: "description", content: "Welcome to Santa Cruz Daily, a place to discover and make plans for living, visiting and adventuring in Santa Cruz."}
- content_for :title do
  Santa Cruz Daily
- content_for :description do
  What's happening in Santa Cruz
.sidebar
  %h5.center Top happenings this week
  %ol
    - for article in @upcoming
      %li
        = link_to article.title, article
        - for event in article.events
          .small.info
            = event.start_date.strftime("%A, %b %d")
            at
            = article.locations.first.line_1 + ","
            = article.locations.first.city
            = link_to "map", "http://maps.apple.com/maps?q=#{article.locations.first.latitude},#{article.locations.first.longitude}", :class => "tag-button"
.flex.with-sidebar
  .summary
    - if @tag.present?
      - if current_user.present?
        - if !@user_tags.include?(params[:tag])
          .add
            = link_to add_tag_path(@tag.name), id: @tag.name, class: 'follow', remote: true, method: :put, data: {toggle_href: "", toggle_class: 'followed'} do
              .tag.center
                = @tag
        - else
          .add.added
            = link_to remove_tag_path(@tag.name), id: @tag.name, class: 'followed', remote: true, method: :put, data: {toggle_href: add_tag_path(@tag.name), toggle_class: 'follow'} do
              .tag.center
                = @tag
    - if @articles.blank?
      - if @tag.present?
        .tag.center
          = params[:tag]
      %p We don't have any articles on this topic yet. Check back, or submit one!
    - for article in @articles
      = render article, index: true

app/views/articles/scrw.html.haml
- content_for :head do
  %meta{property: "og:title", content: "Santa Cruz Restaurant Week on Santa Cruz Daily"}
  %meta{property: "og:site_name", content: "Santa Cruz Restaurant Week on Santa Cruz Daily"}
  %meta{property: "og:description", content: "Where to go for Santa Cruz Restaurant Week"}
  %meta{property: "og:type", content: "website"}
  %meta{property: "og:url", content: request.url}
  %meta{property: "fb:admins", content: "750702877"}
  %meta{name: "twitter:title", content: "Santa Cruz Restaurant Week on Santa Cruz Daily"}
  %meta{name: "twitter:description", content: "Where to go for Santa Cruz Restaurant Week"}
  %meta{name: "twitter:card", content: "summary"}
  %meta{name: "twitter:domain", content: request.url}
  %meta{name: "twitter:creator", content: "@airjoshb"}
  %meta{itemprop: "headline", content: "Santa Cruz Daily"}
  %meta{itemprop: "description", content: "Where to go for Santa Cruz Restaurant Week"}
- content_for :title do
  Santa Cruz Restaurant Week on Santa Cruz Daily
- content_for :description do
  Where to go for Santa Cruz Restaurant Week
%h1 Santa Cruz Restaurant Week

.flex.post
  - for article in @articles
    .flex-element
      -for tag in article.tags.uniq
        .tag= tag
      .mini-article
        %h3
          - if @cart_line_items.to_s.include? article.id.to_s
            %i.star.fa.fa-star.orange
          - else
            =link_to "", article_add_to_path(article_id: article.id, title: article.title), remote: true, class: "star fa fa-star-o add#{article.id}", role: 'button', data: {toggle_href: "", toggle_class: 'fa-star orange'}
          = link_to article.title, article
        - if article.events.present?
          %small
            - if article.events.first.start_date > Time.current
              %strong= custom_time_distance(article.events.first.start_date.to_date)
            - else
              = time_ago_in_words(article.events.first.start_date)
              ago
            = article.events.first.start_date.strftime("%A, %b %d")
            @
            = article.events.first.start_date.strftime("%l:%M%P")
        - if article.locations.present?
          %small
            at
            = article.locations.first.line_1 + ","
            = article.locations.first.city
            = link_to "map", "http://maps.apple.com/maps?q=#{article.locations.first.latitude},#{article.locations.first.longitude}", :class => "tag-button"
        %small
          - if article.publish_date.present?
            = time_ago_in_words(article.publish_date)
            ago
          - if defined?(index) && index
            - if article.recommended_users.present?
              • recommended by
              = article.recommended_users.count
              - if article.recommended_users.count > 1
                people
              - else
                person
        - if article.why.present?
          %small
            %strong Why?
            = article.why
          - if article.tips.present?
            %small
              %strong Tips
              - for tip in article.tips.split(',')
                %small.tip.fa.fa-check= tip
        .tag-button.orange-bgnd.pull-right
          = link_to article do
            more
    :javascript
      $(document).on('ajax:success', 'a.add#{article.id}', function(status, data, xhr) {
        $("a.add#{article.id}").each(function() {
          var $a, allclass, c, href;
          $a = $(this);
          href = $a.attr('href');
          c = $a.attr('class');
          allclass = c.split('')[0];
          $a.attr('href', $a.data('toggle-href'));
          $a.removeClass('fa-star-o');
          $a.toggleClass($a.data('toggle-class'));
          $a.data('toggle-href', href);
        });
      });

app/views/articles/show.html.haml
- content_for :html do
  http://schema.org/Article
- content_for :head do
  %meta{property: "og:title", content: @article.title}
  %meta{property: "og:site_name", content: "Santa Cruz Daily"}
  %meta{property: "og:description", content: Nokogiri::HTML.parse(markdown(@article.body)).css('p').first.text }
  %meta{property: "og:type", content: "article"}
  %meta{property: "og:url", content: article_url}
  %meta{property: "og:image", content: @article.image.hero.url}
  -if @article.publish_date.present?
    %meta{property: "article:published_time", content: @article.publish_date.to_time.iso8601}
  %meta{property: "article:section", content: @article.tags.first}
  %meta{property: "article:tag", content: @article.tag_list}
  %meta{property: "fb:admins", content: "750702877"}
  %meta{name: "twitter:title", content: @article.title}
  %meta{name: "twitter:description", content: Nokogiri::HTML.parse(markdown(@article.body)).css('p').first.text }
  %meta{name: "twitter:image", content: @article.image.hero.url}
  %meta{name: "twitter:card", content: "summary_large_image"}
  %meta{name: "twitter:url", content: article_url}
  %meta{name: "twitter:creator", content: "@airjoshb"}
  %meta{itemprop: "headline", content: @article.title}
  %meta{itemprop: "description", content: Nokogiri::HTML.parse(markdown(@article.body)).css('p').first.text }
  %meta{itemprop: "image", content: @article.image.hero.url}
  -if @article.publish_date.present?
    %meta{itemprop: "datePublished", content: @article.publish_date.to_time.iso8601}
- content_for :title do
  #{@article.title} | Santa Cruz Daily
- content_for :description do
  = Nokogiri::HTML.parse(markdown(@article.body)).css('p').first.text
.main
  = render @article
- if @article.next.present?
  .next
    %h4= "Read Next" unless @article.next.blank?
    .well
      %span.title= link_to @article.next.title, article_path(@article.next)
      %small
        - if @article.next.recommended_users.present?
          • recommended by
          = @article.next.recommended_users.count
          - if @article.next.recommended_users.count > 1
            people
          - else
            person
      %p= Nokogiri::HTML.parse(markdown(@article.next.body)).css('p').first.text
      .readnext
        = link_to @article.next do
          continue reading
        %i.fa.fa-arrow-right