config/routes.rb
Rails.application.routes.draw do
  get 'visitors/index'

  get '/sitemap' => 'visitors#sitemap',
      defaults: { :format => 'xml' }

  get '/food' => 'articles#food',
      defaults: { :format => 'xml' }
  get '/live-events' => 'articles#live_events',
      defaults: { :format => 'xml' }
  get '/adventure' => 'articles#adventure',
      defaults: { :format => 'xml' }
  get '/shopping' => 'articles#shopping',
      defaults: { :format => 'xml' }

  resources :share_emails

  get '/santa-cruz-restaurant-week', to: 'articles#scrw', as: :santa_cruz_restaurant_week
  get '/lineup/food', to: 'articles#index', as: :food_lineup, :defaults => { :tag => 'food' }
  get '/lineup/live-events', to: 'articles#index', as: :live_events_lineup, :defaults => { :tag => 'live events' }
  get '/lineup/adventure', to: 'articles#index', as: :adventure_lineup, :defaults => { :tag => 'adventure' }
  get '/lineup/shopping', to: 'articles#index', as: :shopping_lineup, :defaults => { :tag => 'shopping' }

  resources :articles, :path => "/lineup" , :except => [:new, :create, :edit, :update, :destroy] do
    resources :events
    resources :locations
    get 'add/:article_id', to: 'articles#add', as: :add_to
    get 'remove/:article_id', to: 'articles#remove', as: :remove_from
    put :recommend, on: :member
    put :unrecommend, on: :member
    get 'change_status/:status', to: 'articles#change_status', as: :change_status, on: :member
  end

  get 'send_mail', to: 'articles#send_mail', as: :send_mail

  get 'tagged' => 'articles#tagged', :as => 'tagged'

  mount StripeEvent::Engine => '/stripe'


  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: 'omniauth_callbacks'}, skip: [:sessions, :registrations]

  #->Prelang (user_login:devise/stylized_paths)
  devise_scope :user do
    root to: 'users/registrations#new'
    get 'admin/users/:id', to: 'admin/users#edit', as: :edit_admin_user
    put 'admin/users/:id', to: 'admin/users#update'
    get 'admin/users', to: 'admin/users#new', as: :new_admin_user
    put 'add_tag/:tag', to: 'users/registrations#add_tag', as: :add_tag
    put 'remove_tag/:tag', to: 'users/registrations#remove_tag', as: :remove_tag
    delete "admin/users/:id" => "admin/users#destroy", as: :delete_user_admin
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    match '/users/:id/finish_signup' => 'users/registrations#finish_signup', via: [:get, :patch], :as => :finish_signup


    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
    post 'admin/add_role/:id/:role', to: 'admin/users#add_role', as: :add_role


  end

  authenticated :user do
    devise_scope :user do
      root to: 'articles#index', as: :authenticated
    end
  end

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    get 'article/:id', to: 'articles#edit', as: :edit_article
    get 'articles', to: 'articles#new', as: :new_article
    delete 'articles/:id', to: 'articles#destroy', as: :destroy_article
    put 'articles', to: 'articles#create'
    patch 'article/:id', to: 'articles#update'
    put 'article/:id', to: 'articles#update'
    delete 'articles/:id', to: 'articles#delete', as: :delete_article
  end


  # mount using default path: /email_processor
  mount_griddler


end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_filter :authenticate_user!


  def index
    @articles = Article.all
    @users = User.all
    @deleted = Article.status(4)
    @roles = User.roles
    respond_to do |format|
      format.js
      format.html
    end
  end



end

app/views/admin/dashboard/_articles.html.haml
%ul
  - for article in @articles
    - unless article.statuses.find_by_status(4)
      %li
        = link_to article_path(article) do
          %i.fa.fa-eye
        = link_to admin_edit_article_path(article) do
          %i.fa.fa-edit
        = article.title
        %div
          %span{:class => [article.statuses.first.status, 'small']}= article.statuses.first.status
          - if article.statuses.first.published?
            = link_to "delete", change_status_article_path(article, status: "deleted"), remote: true, class: "btn2 deleted tag small"
          - elsif article.statuses.first.pending?
            = link_to "approve", change_status_article_path(article, status: "approved"), remote: true, class: "btn2 approved tag small"
            = link_to "decline", change_status_article_path(article, status: "declined"), remote: true, class: "btn2 declined tag small"

            = link_to "delete", change_status_article_path(article, status: "deleted"), remote: true, class: "btn2 deleted tag small"
          - elsif article.statuses.first.declined?
            = link_to "approve", change_status_article_path(article, status: "approved"), remote: true, class: "btn2 approved tag small"
            = link_to "delete", change_status_article_path(article, status: "deleted"), remote: true, class: "btn2 deleted tag small"
          - elsif article.statuses.first.approved?
            = link_to "publish", change_status_article_path(article, status: "published"), remote: true, class: "btn2 published tag small"
            = link_to "delete", change_status_article_path(article, status: "deleted"), remote: true, class: "btn2 deleted tag small"
          = link_to "destroy", admin_destroy_article_path(article), method: :delete, remote: true, class: "btn tag-button destroyed small"
        %hr

app/views/admin/dashboard/_deleted.html.haml
%ul
  - for article in @deleted
    %li
      = link_to article_path(article) do
        %i.fa.fa-eye
      = article.title
      = article.statuses.last.status
= link_to "hide deleted articles", "", remote: true, class: "btn4"

app/views/admin/dashboard/index.html.haml
%h1 Dashboard
%h2 Articles
#articles
  = render 'articles'
  = link_to "Show deleted articles", "", remote: true, class: "btn3"
  #deleted_articles


%h2 Users
= link_to 'Add User', new_admin_user_path
%ul
  - for user in @users
    %li
      = link_to edit_admin_user_path(user) do
        %i.fa.fa-edit
      = user.email
      %div
        = select_tag "roles", options_for_select(@roles.keys.to_a, user.role), class: "role-select", data: { "user-id" => user.id }
        = link_to "delete", delete_user_admin_path(user), method: :delete, remote: true, class: "tag-button destroyed small"
    %hr

:javascript
  $(document).on('ajax:success', '.btn', function(status, data, xhr) {
    $(this).parents('li').fadeOut();
    return false;

  });
  $(".role-select").on("change", function() {
    var role, user_id;
    user_id = $(this).data("user-id");
    role = $(this).val();
    return $.post("/admin/add_role/" + user_id + "/" + role);
  });

app/views/admin/dashboard/index.js.erb
$(document).on('ajax:success', '.btn3', function(status, data, xhr) {
    $("#deleted_articles").show();
    $("#deleted_articles").html("<%= escape_javascript(render partial: 'deleted', locals: { deleted: @deleted } ) %>");
  });

$(document).on('ajax:success', '.btn4', function(status, data, xhr) {
    $("#deleted_articles").hide();
  });