config/routes.rb
Rails.application.routes.draw do
  get 'visitors/index'

  get '/sitemap' => 'visitors#sitemap',
      defaults: { :format => 'xml' }

  get '/food' => 'articles#food',
      defaults: { :format => 'xml' }
  get '/live-events' => 'articles#live_events',
      defaults: { :format => 'xml' }
  get '/adventure' => 'articles#adventure',
      defaults: { :format => 'xml' }
  get '/shopping' => 'articles#shopping',
      defaults: { :format => 'xml' }

  resources :share_emails

  get '/santa-cruz-restaurant-week', to: 'articles#scrw', as: :santa_cruz_restaurant_week
  get '/lineup/food', to: 'articles#index', as: :food_lineup, :defaults => { :tag => 'food' }
  get '/lineup/live-events', to: 'articles#index', as: :live_events_lineup, :defaults => { :tag => 'live events' }
  get '/lineup/adventure', to: 'articles#index', as: :adventure_lineup, :defaults => { :tag => 'adventure' }
  get '/lineup/shopping', to: 'articles#index', as: :shopping_lineup, :defaults => { :tag => 'shopping' }

  resources :articles, :path => "/lineup" , :except => [:new, :create, :edit, :update, :destroy] do
    resources :events
    resources :locations
    get 'add/:article_id', to: 'articles#add', as: :add_to
    get 'remove/:article_id', to: 'articles#remove', as: :remove_from
    put :recommend, on: :member
    put :unrecommend, on: :member
    get 'change_status/:status', to: 'articles#change_status', as: :change_status, on: :member
  end

  get 'send_mail', to: 'articles#send_mail', as: :send_mail

  get 'tagged' => 'articles#tagged', :as => 'tagged'

  mount StripeEvent::Engine => '/stripe'


  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: 'omniauth_callbacks'}, skip: [:sessions, :registrations]

  #->Prelang (user_login:devise/stylized_paths)
  devise_scope :user do
    root to: 'users/registrations#new'
    get 'admin/users/:id', to: 'admin/users#edit', as: :edit_admin_user
    put 'admin/users/:id', to: 'admin/users#update'
    get 'admin/users', to: 'admin/users#new', as: :new_admin_user
    put 'add_tag/:tag', to: 'users/registrations#add_tag', as: :add_tag
    put 'remove_tag/:tag', to: 'users/registrations#remove_tag', as: :remove_tag
    delete "admin/users/:id" => "admin/users#destroy", as: :delete_user_admin
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    match '/users/:id/finish_signup' => 'users/registrations#finish_signup', via: [:get, :patch], :as => :finish_signup


    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
    post 'admin/add_role/:id/:role', to: 'admin/users#add_role', as: :add_role


  end

  authenticated :user do
    devise_scope :user do
      root to: 'articles#index', as: :authenticated
    end
  end

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    get 'article/:id', to: 'articles#edit', as: :edit_article
    get 'articles', to: 'articles#new', as: :new_article
    delete 'articles/:id', to: 'articles#destroy', as: :destroy_article
    put 'articles', to: 'articles#create'
    patch 'article/:id', to: 'articles#update'
    put 'article/:id', to: 'articles#update'
    delete 'articles/:id', to: 'articles#delete', as: :delete_article
  end


  # mount using default path: /email_processor
  mount_griddler


end

app/views/layouts/_favicon.html.haml
- %w(76 120 152 180).each do |size|
  = favicon_link_tag "apple-icon-#{size}x#{size}.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "#{size}x#{size}"
- %w(16 32).each do |size|
  = favicon_link_tag "favicon-#{size}x#{size}.png", rel: 'icon', type: 'image/png', sizes: "#{size}x#{size}"

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "What's happening in Santa Cruz | Santa Cruz Daily"
    = favicon_link_tag 'ico/favicon.ico'
    = render 'layouts/favicon'
    %link{href: "http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,700,600,300,800", rel: "stylesheet", type: "text/css"}
    %link{href: "http://fonts.googleapis.com/css?family=Arapey:400italic,400", rel: "stylesheet", type: "text/css"}
    %link{href: "http://fonts.googleapis.com/css?family=Comfortaa", rel: "stylesheet", type: "text/css"}
    %meta{content: "yes", name: "apple-mobile-web-app-capable"}
    %meta{content: "black", name: "apple-mobile-web-app-status-bar-style"}
    %meta{:content => content_for?(:description) ? yield(:description) : "Welcome to Santa Cruz Daily, a place to discover and make plans for living, visiting and adventuring in Santa Cruz.", :name => "description"}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    - if Rails.env.production?
      :javascript
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-41484403-3', 'auto');
        ga('send', 'pageview');

        window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var n=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(n?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var o=document.getElementsByTagName("script")[0];o.parentNode.insertBefore(a,o);for(var r=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["clearEventProperties","identify","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=r(p[c])}; heap.load("791374028");
    = csrf_meta_tags
    = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    / NAVIGATION
    %nav#nav.desktop
      .nav-group
        .logo= link_to image_tag("santa-cruz-daily-octopus.png"), root_path
        - if @article.present? or params[:tag].present? or controller.controller_name == "registrations" && controller.action_name == "edit"
          .nav-group
            .nav-element
              = link_to articles_path do
                %i.fa.fa-caret-left
                back to the lineup
        - if current_user.present?
          .nav-group
            .nav-element
              = link_to edit_registration_path(current_user) do
                - if current_user.identities.present?
                  .nav-icon= image_tag current_user.identities.first.avatar, :class => "circle"
                .nav-text
                  - if  current_user.identities.present?
                    = current_user.identities.first.nickname
                  - else
                    = current_user.username || current_user.email
          .nav-group
            .nav-element
              = link_to "Logout", destroy_user_session_path, method: :delete
              %i.fa.fa-chevron-circle-right
        - else
          .nav-group
            .nav-element
              = link_to "Login", new_user_session_path
              %i.fa.fa-chevron-circle-right
          .nav-group
            %ul
              %li.nav-element= link_to "live events", live_events_lineup_path
              %li.nav-element= link_to "food", food_lineup_path
              %li.nav-element= link_to "adventure", adventure_lineup_path
              %li.nav-element= link_to "shopping", shopping_lineup_path

      .nav-group
        - if current_user.present?
          .nav-title
            Top Interests
          - for tag in @tags
            .nav-element
              .nav-text= link_to tag, articles_path(:tag => tag.name)
          %label.nav-title.margin-toggle{:for => "interests"}
            See all interests
          %input#interests.margin-toggle{:type => "checkbox"}
          %span.note
            - for tag in current_user.tags
              .nav-element
                .nav-text= link_to tag, articles_path(:tag => tag.name)

      .nav-group
        .center.social
          = link_to "http://twitter.com/santacruzdaily", target: '_blank' do
            %i.fa.fa-twitter.fa-2x.large
          = link_to "http://instagram.com/thesantacruzdaily", target: '_blank' do
            %i.fa.fa-instagram.fa-2x.large
          = link_to "http://facebook.com/santacruzdaily", target: '_blank' do
            %i.fa.fa-facebook.fa-2x.large
      .nav-group.scd
        .nav-title
          Santa Cruz Daily ©2015
    %nav#nav.mobile
      - if current_user.present?
        .topics
          %ul
            - for tag in @tags
              %li= link_to tag, articles_path(:tag => tag.name)
            %li
              = link_to destroy_user_session_path, method: :delete do
                Logout
                %i.fa.fa-chevron-circle-right
        .login
          = link_to edit_registration_path(current_user) do
            - if current_user.identities.present?
              = image_tag current_user.identities.first.avatar, :class => "circle"
            - else
              Account
      - else
        .topics
          %ul
            %li= link_to "live events", live_events_lineup_path
            %li= link_to "food", food_lineup_path
            %li= link_to "adventure", adventure_lineup_path
            %li= link_to "shopping", shopping_lineup_path


    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
      .logotype
        = link_to root_path do
          = image_tag("santa-cruz-daily-octopus.png")
          Santa Cruz Daily
        - if @tag.present? and !@current_user.present?
          .tag.center
            = @tag
        - if controller.action_name == "scrw" or controller.action_name == "show"
          = link_to "" do
            %i.fa.fa-3x.fa-envelope-o
          #modal.lineup-popover
            = render 'lineup_email'


      = yield

app/views/layouts/favicon.html.haml
- %w(76 120 152 180).each do |size|
  = favicon_link_tag "apple-icon-#{size}x#{size}.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "#{size}x#{size}"
- %w(16 32).each do |size|
  = favicon_link_tag "favicon-#{size}x#{size}.png", rel: 'icon', type: 'image/png', sizes: "#{size}x#{size}"

app/views/layouts/preview.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "What's happening in Santa Cruz"
    = favicon_link_tag 'ico/favicon.ico'
    %link{href: "ico/apple-touch-icon.png", rel: "apple-touch-icon"}
    %link{href: "ico/apple-touch-icon-57x57.png", rel: "apple-touch-icon", sizes: "57x57"}
    %link{href: "ico/apple-touch-icon-60x60.png", rel: "apple-touch-icon", sizes: "60x60"}
    %link{href: "ico/apple-touch-icon-72x72.png", rel: "apple-touch-icon", sizes: "72x72"}
    %link{href: "ico/apple-touch-icon-76x76.png", rel: "apple-touch-icon", sizes: "76x76"}
    %link{href: "ico/apple-touch-icon-114x114.png", rel: "apple-touch-icon", sizes: "114x114"}
    %link{href: "ico/apple-touch-icon-120x120.png", rel: "apple-touch-icon", sizes: "120x120"}
    %link{href: "ico/apple-touch-icon-144x144.png", rel: "apple-touch-icon", sizes: "144x144"}
    %link{href: "ico/apple-touch-icon-152x152.png", rel: "apple-touch-icon", sizes: "152x152"}
    %link{:href => "/android-chrome-192x192.png", :rel => "icon", :sizes => "192x192", :type => "image/png"}/
    %link{:href => "/favicon-96x96.png", :rel => "icon", :sizes => "96x96", :type => "image/png"}/
    %link{:href => "/favicon-16x16.png", :rel => "icon", :sizes => "16x16", :type => "image/png"}/
    %link{href: "http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,700,600,300,800", rel: "stylesheet", type: "text/css"}
    %link{href: "http://fonts.googleapis.com/css?family=Comfortaa", rel: "stylesheet", type: "text/css"}
    %meta{content: "yes", name: "apple-mobile-web-app-capable"}
    %meta{content: "black", name: "apple-mobile-web-app-status-bar-style"}
    %meta{:content => content_for?(:description) ? yield(:description) : "Curated and personalized content about the best things to do in Santa Cruz", :name => "description"}
    = stylesheet_link_tag "preview", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
    - if Rails.env.production?
      :javascript
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-41484403-3', 'auto');
        ga('send', 'pageview');
  %body
    = yield